#!/bin/bash

#version 3.1
#Last updated on Jun 26, 2024

# Small tools checking whether and why a user is blocked on the system.
# Please contact Si Liu (siliu@tacc.utexas.edu)
# If you have any questions or concerns.

if [ "$#" -ne 1 ];
then 
    echo "Illegal number of parameters!"
	echo "Please launch the command as: whyblock joe"
    echo "or list all blocked users by: whyblock all"
    echo "or list all blocked users (pvc nodes) by: whyblock pvc"
	echo "or list all blocked users (spr nodes) by: whyblock spr"
    echo "   "
    echo "Contact Si Liu for any questions or concerns."
    exit
fi

if [ "$1" == "-h" ] || [ "$1" == "-H" ] || [ "$1" == "--help" ] ;
then
	echo "TACC tool to check why a user is blocked on the system"
	echo "Please launch the command as: whyblock joe"
	echo "or list all users prevented from submission: whyblock all"
	echo "or list all users prevented from submission (pvc nodes): whyblock pvc"
	echo "or list all users prevented from submission (spr nodes): whyblock spr"
	echo "whyblock -h or whyblock --help for this help information"
	echo "   "
	echo "Contact Si Liu (siliu@tacc.utexas.edu) for any questions or concerns."
	exit
fi

if [ "$1" == "all" ] || [ "$1" == "All" ] || [ "$1" == "ALL" ] ;
then
	echo "Users who can not submit jobs:"
	all=`grep "ALL = " /etc/slurm/tacc_filter_options | sed "s/ALL = //g" | sed 's/!root//g' | sed 's/ !!/ /g'`
	all=${all//\'/}
	echo $all
	exit 
fi

if [ "$1" == "pvc" ] || [ "$1" == "PVC" ] ;
then
	echo "Users who can not submit jobs to PVC nodes:"
	all=`grep "pvc = " /etc/slurm/tacc_filter_options | sed "s/pvc = //g" | sed 's/!root//g' | sed 's/ !!/ /g'`
	all=${all//\'/}
	echo $all
	exit
fi

if [ "$1" == "spr" ] || [ "$1" == "SPR" ] ;
then
	echo "Users who can not submit jobs to SPR nodes:"
	all=`grep "spr = " /etc/slurm/tacc_filter_options | sed "s/spr = //g" | sed 's/!root//g' | sed 's/ !!/ /g'`
	all=${all//\'/}
	echo $all
	exit
fi


user=`echo $1 | tr '[:upper:]' '[:lower:]'`

host=`hostname`

if [[ ! $host =~ 'stampede3' ]]; then
	userinfo=`/bin/awk -F: -v user="$user" '$1 == user {print $0}' </etc/passwd `

	if [[ -z $userinfo ]]; then
		echo "$user is not a known user."
		exit
	else
		echo -e "User info:\n"$userinfo
		echo ""
	fi
fi

### Can not login: blocked by Frontera administrators
if [[ ! $host =~ 'stampede3' ]]; then
	block_login=`grep "bin_" /etc/passwd | /bin/awk -F: -v user="$user" '$1 == user'`
	### echo $block_login
	if [[ -n $block_login ]]; then
		echo "The user $user's account is locked."
		echo "Please check https://tas.tacc.utexas.edu/TACCAdministration/ for more details."
		exit 
	fi
fi

###Old checking rules:
###block_normal=`awk '/ALL = /,/ALL = /' /etc/slurm/tacc_filter_options  | grep $user`
###block_large=`grep "^largemem" /etc/slurm/tacc_filter_options | grep $user`

##Whether the user is blocked from general submission:
block_normal=`awk '/ALL = /,/ALL = /' /etc/slurm/tacc_filter_options | awk '{gsub(/ /, "", $0); print substr($0,7,length($0)-7)}' | awk -v user="$user" 'BEGIN {FS="!!"}; {for (i=1; i<=NF; i++) if ($i == user) {print $0}}'`
block_spr=`awk '/spr = /,/spr = /' /etc/slurm/tacc_filter_options | awk '{gsub(/ /, "", $0); print substr($0,7,length($0)-7)}' | awk -v user="$user" 'BEGIN {FS="!!"}; {for (i=1; i<=NF; i++) if ($i == user) {print $0}}'`
block_pvc=`awk '/pvc = /,/pvc = /' /etc/slurm/tacc_filter_options | awk '{gsub(/ /, "", $0); print substr($0,7,length($0)-7)}' | awk -v user="$user" 'BEGIN {FS="!!"}; {for (i=1; i<=NF; i++) if ($i == user) {print $0}}'`

##whether the user is blocked from largemem queue submission:
##block_large=`awk '($1=="largemem")' /etc/slurm/tacc_filter_options | awk '{gsub(/ /, "", $0);print substr($0,12, length($0)-12)}' |  awk -v user="$user" 'BEGIN {FS="!!"}; {for (i=1; i<=NF; i++) if ($i == user) {print $0}}'`

##whether the user is blocked from mic queue submission
##block_mic=`awk '($1=="normal-mic" || $1=="normal-2mic")' /etc/slurm/tacc_filter_options | awk '{gsub(/ /, "", $0); print substr($0,14, length($0)-14)}' |  awk -v user="$user" 'BEGIN {FS="!!"}; {for (i=1; i<=NF; i++) if ($i == user) {print $0}}'`

if [[ -n $block_normal ]]; then
	echo "$user is not allowed to submit jobs on the system."
	echo "Possible block reason from System Administrators:" 
	awk '/# Disabled/,/ALL = /' /etc/slurm/tacc_filter_options  | grep $user | sed '$d'
fi

if [[ -n $block_spr ]]; then
	echo "$user is not allowed to submit jobs to SPR nodes on the system."
	echo "Possible block reason from System Administrators:" 
	awk '/# Disabled/,/ALL = /' /etc/slurm/tacc_filter_options  | grep $user
fi

if [[ -n $block_pvc ]]; then
	echo "$user is not allowed to submit jobs to PVC nodes on the system."
	echo "Possible block reason from System Administrators:" 
	awk '/# Disabled/,/ALL = /' /etc/slurm/tacc_filter_options  | grep $user
fi

if [[ -z $block_normal && -z $block_spr && -z $block_pvc && -z $block_large && -z $block_mic ]]; then
	echo "$user is NOT blocked by the system administrators at this time."
fi

