#!/usr/bin/env python      

import os, sys, re
from datetime import *
from util       import run_cmd, capture,syshost
 
host=syshost()
userid=capture("whoami").rstrip()

if (host=="stampede" or host=="maverick" or host=="ls5"):
    TACC_ACC_DIR="/usr/local/etc/"
else:
    print("Unkonwn system")
    sys.exit(1)

proj_map=TACC_ACC_DIR+"project.map"
projuser_map=TACC_ACC_DIR+"projectuser.map"
projbalance_map=TACC_ACC_DIR+"projectbalance.map"
usage_map=TACC_ACC_DIR+"usage.map"
 
grepcmd="""awk -v user=%s '$1 == user {print $0}' %s """ %(userid,projuser_map)
myprojects=capture(grepcmd).split()
if len(myprojects) < 2:
    self.error_message+="\tError: "+"No valid allocation\n"
    sys.exit(0)

print("Allocation       Availa SUs         Expires")
for proj in myprojects[1:]:
    grepcmd="grep %s$ %s" %(proj,proj_map)
    proj_name_all=capture(grepcmd).split()
    
    if proj_name_all:
        proj_name=proj_name_all[0]
        grepcmd="awk -F: '{ if ($1==\"%s\") print}' %s" %(proj_name,usage_map)
        
        usage_report=capture(grepcmd).split(":")
        if len(usage_report) < 6:
            print("\033[1;33m\tWarning: Valid allocation detected.\033[0m")
            sys.exit(1)
        exp_date=usage_report[3].split("-")
        exp_date_f=date(int(exp_date[0]), int(exp_date[1]), int(exp_date[2]))
        today = date.today()

        cur_bal=float(usage_report[6])
        print("%-15s  %10s      %10s" %(proj_name,cur_bal,exp_date_f))

